platform :ios, '8.0'
target 'CarWashing' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'SDWebImage', '~> 3.7.2'
  pod 'JSONModel', '~> 1.7.0'
  pod 'FMDB', '~> 2.7.2'
  pod 'SDAutoLayout'
  pod 'AMap2DMap', '~> 4.6.0'
  pod 'IQKeyboardManager'
  pod 'DZNEmptyDataSet'
  pod 'MJRefresh'
  pod "GCCycleScrollView"
  pod 'WechatOpenSDK', '~> 1.8.0'
  pod 'AMapLocation', '~> 2.4.0'
  pod 'MJExtension', '~> 3.0.13'
  pod 'AliPay_SDK', '~> 3.0.0'
  pod 'OpenSSL-for-iOS', '~> 1.0.2.d.1'
  pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
end
